GameNet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('accounts.urls')),
    path('games/',include('games.urls')),
    path('news/',include('news.urls')),
    path('reviews/',include('reviews.urls')),
    path('moderation/',include('moderation.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path("your_news/", views.your_news, name="yourNews"),
    path("add/", views.add, name='addNews'),
    path("delete/<id>/", views.delete, name='deleteNews'),
    path("edit/<id>/", views.edit, name='editNews'),
    path("<id>/", views.news_site, name="news"),
    path("",views.news_list, name="newsList")
]

reviews/urls.py
from django.urls import path
from reviews import views

urlpatterns = [
    path("your_reviews/", views.your_reviews, name="yourReviews"),
    path("add/", views.add, name='addReviews'),
    path("delete/<id>/", views.delete, name='deleteReviews'),
    path("edit/<id>/", views.edit, name='editReviews'),
    path("<id>/", views.reviews_site, name="review"),
    path("",views.reviews_list, name="reviewsList")
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from games.models import Game
from django_ckeditor_5.fields import CKEditor5Field
from cloudinary.models import CloudinaryField
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Review(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    points = models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    lead = models.TextField(max_length=1024, default="Zapowiedź")
    image = CloudinaryField("review_image", null=True, blank=True)
    content = CKEditor5Field()
    summary = models.TextField(max_length=1024, default="Podsumowanie")
    created_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

reviews/forms.py
from django.forms import ModelForm

from .models import Review
from django_ckeditor_5.widgets import CKEditor5Widget

class ReviewForm(ModelForm):   
    class Meta:
        model = Review
        fields = ["title","game","lead","points","image","content","summary"]
        widgets = {
              "content": CKEditor5Widget()
          }

reviews/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from babel.dates import format_datetime

from .models import Review
from .forms import ReviewForm
from .decorators import check_if_reviewer

# Create your views here.

def reviews_site(request, id):
    reviews_object = Review.objects.get(pk=id)

    context = {'review': reviews_object}
    return render(request, "reviews/review_site.html", context)

def reviews_list(request):
    page = request.GET.get('page',1)

    paginator = Paginator(Review.objects.all().order_by("-edit_date"), 10)

    try:
        reviews_objects = paginator.get_page(page)
    except PageNotAnInteger:
        reviews_objects = paginator.get_page(1)
    except EmptyPage:
        reviews_objects = paginator.page(paginator.num_pages)

    context = {'reviews_objects': reviews_objects}
    return render(request, "reviews/reviews_list.html",context)

@login_required
def your_reviews(request):
    user = request.user
    check_if_reviewer(user)
    user_reviews = Review.objects.filter(author=user).order_by('-edit_date')

    last_edited = []
    for last in user_reviews.values_list("edit_date",flat=True):
        last_edited.append(format_datetime(last, locale="pl_PL"))

    context = {'user_reviews': zip(user_reviews, last_edited) if user_reviews.count() != 0 else None}
    return render(request, "reviews/your_reviews.html", context)

@login_required
def add(request):
    check_if_reviewer(request.user)

    form = ReviewForm()

    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            reviews = form.save(commit=False)
            reviews.author = request.user
            reviews.save()
            return redirect('yourReviews')

    context = {'form': form}
    return render(request, "reviews/add_edit.html", context)


@login_required
def edit(request, id):
    check_if_reviewer(request.user)

    review = Review.objects.get(pk=id)
    form = ReviewForm(instance=review)

    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()
            return redirect('yourReviews')

    context = {'form': form, 'edit': True, 'id': id}
    return render(request, "reviews/add_edit.html", context)


@login_required
def delete(request, id):
    check_if_reviewer(request.user)

    if request.method == "POST":
        review = Review.objects.get(pk=id)
        review.delete()
        return redirect("yourReviews")
    return render(request, "reviews/confirm_delete.html")

templates/reviews/add_edit.html
{% include '../head.html' %}
{% include '../navbar.html' %}

{% load crispy_forms_tags %}
{% load static %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<section>
    <div class="container-lg mt-4">
        <h2>{% if edit %}Edytuj recenzję{% else %}Dodaj recenzję{% endif %}</h2>
        <div class="my-3 mb-4 px-3">
            <form action="{% if edit %}{% url 'editReviews' id %}{% else %}{% url 'addReviews' %}{% endif %}" id="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <button class="btn btn-primary my-3" type="submit">{% if edit %}Edytuj{% else %}Dodaj{% endif %}</button>
                    <a href="{% url 'yourReviews' %}" class="btn btn-secondary my-3">Anuluj</a>

                    <div class="row">
                        <div class="col">
                            <label for="id_title" class="my-2 fw-bold">Tytuł</label>
                            {{form.title|as_crispy_field}}
                        </div>
                        <div class="col">
                            <label for="id_game" class="my-2 fw-bold">Gra</label>
                            {{form.game|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row my-2">
                        <div class="col">
                            <label for="id_lead" class="my-2 fw-bold">Zapowiedź</label>
                            {{form.lead|as_crispy_field}}
                        </div>
                        <div class="col">
                            <label for="id_points" class="my-2 fw-bold">Ocena (1-10)</label>
                            {{form.points|as_crispy_field}}
                        </div>
                    </div>                    
                    <div class="row my-2">
                        <label for="id_image" class="my-2 fw-bold">Dodaj zdjęcie</label>
                        {{form.image|as_crispy_field}}
                    </div>
                    <div class="row my-2">
                        <label for="id_content" class="my-2 fw-bold">Treść</label>
                        <div class="text-center">
                            {{form.content}}
                        </div>
                    </div>
                    <div class="row my-2">
                        <label for="id_content" class="my-2 fw-bold">Treść</label>
                        {{form.summary}}
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<script>
    document.getElementById("id_lead").rows = "5";
    document.getElementById('form').noValidate = true;
</script>

{% include '../footer.html' %}

templates/reviews/confirm_delete.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<div class="container-lg mt-5">
    <h2 class="text-center mb-5">Czy na pewno chcesz usunąć news?</h2>
    <div class="row d-flex justify-content-center">
        <div class="col-7">
            <form method="POST" action="">
                {% csrf_token %}
                <div class="row mx-auto">
                    <div class="col d-grid">
                        <button class="btn btn-danger btn-lg" type="submit">Tak</button>
                    </div>
                    <div class="col d-grid">
                        <a class="btn btn-secondary btn-lg" href="{% url 'yourReviews' %}">Nie</a>
                    </div>
                </div>
                
            </form>

        </div>
    </div>
</div>

{% include '../footer.html' %}

templates/reviews/review_site.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section>
    <div class="container border rounded my-4">
        <div class="row p-3 text-start ms-5 mb-4 mt-3 w-75">
            <h2 class="my-4">{{review.title}}</h2>
            <div class="col">
                <h3 class="fs-5 mt-2">{{review.lead}}</h3>
            </div>
        </div>
        <div class="row mb-4">
            {% if review.image %}
            <img src="{{ review.image.url }}" class="image-fluid" style="max-height: 400px; object-fit: cover;" alt="...">
            {% endif %}
        </div>
        <div class="row mx-5 mt-4" id="content">
            {{review.content|safe}}
            <div class="card m-3">
                <div class="card-body">
                    <h4 class="card-title">Podsumowanie</h4>
                    <div class="row m-3">
                        <div class="col-1">
                            <h5>Ocena</h5>
                            <div style="width: 50px; height: 50px;" class="fs-2 mt-3 bg-{% if review.points <= 3.3 %}danger{% elif review.points < 6.6 %}warning{% else %}success{% endif %} rounded-circle text-light d-flex justify-content-center">
                                <div class="mx-2">{{review.points}}</div>
                            </div>
                        </div>
                        <div class="col border-start border-end p-4">
                            {{review.summary}}
                        </div>
                        <div class="col-4 pb-3 mt-0 ms-3 text-center">
                            <a href="{% url 'game' id=review.game.pk %}" class="text-reset text-decoration-none">
                                <h5 class="mb-3">{{review.game.title}}</h5>
                                {% if review.game.image %}
                                <img src="{{ review.game.image.url }}" alt="Game image" class="img-fluid h-75 rounded"/>
                                {% elif review.game.image_link %}
                                <img src="{{ review.game.image_link }}" alt="Game image" class="img-fluid rounded"/>
                                {% else %}
                                ----
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <p class="text-end text-muted my-3 fs-4">Autor: {% if review.author %}{{review.author}}{% else %}<span class="text-muted">[Konto usunięte]</span>{% endif %}</p>
        </div>
    </div>
</section>

{% include '../footer.html' %}

templates/reviews/reviews_list.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section>
    <div class="container-lg">
        <h2 class="my-4">Najnowsze recenzje</h2>

        {% if reviews_objects %}
        {% for review in reviews_objects %}
        <a href="{% url 'review' id=review.pk %}" class="text-reset text-decoration-none">
        <div class="card my-3">
            <div class="row">
                <div class="col-3">
                    {% if review.image %}
                    <img src="{{ review.image.url }}" alt="review image" class="img-fluid rounded-start"/>
                    {% else %}
                    <img src="https://res.cloudinary.com/dzxo9mpqc/image/upload/v1656005252/no-photo-available_gyrfyl.png" alt="review image" class="img-fluid rounded-start">
                    {% endif %}
                </div>
                <div class="col">
                    <div class="card-body">
                        <h5 class="card-title">{{review.title}}</h5>
                        <p class="card-text">{{review.lead|slice:":256"|safe}}{% if review.lead|length > 256 %}...{% endif %}</p>
                        <p class="text-muted">Autor: {{review.author.username}}</p>
                    </div>
                </div>
            </div>
        </div>
        </a>
        
        {% endfor %}
        {% else %}

        <div class="card my-3">
            <div class="card-body">
                <h3 class="fs-4">Brak recenzji</h3>
                <span class="text-muted">Nie dodano jeszcze żadnych recenzji</span>
            </div>
        </div>
        
        {% endif %}

    </div>
</section>

<section>
    <div class="container my-4">
        <div class="btn-toolbar d-flex justify-content-center">
            <div class="btn-group mx-3">
                {% if reviews_objects.has_previous %}
                    <a href="?page=1" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-left"></i></a>
                    <a href="?page={{ reviews_objects.previous_page_number }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-left"></i></a>
                {% endif %}
            </div>
                <span class="border rounded border-secondary text-muted p-2">{{reviews_objects.number}}</span>
            <div class="btn-group mx-3">
                {% if reviews_objects.has_next %}
                    <a href="?page={{ reviews_objects.next_page_number }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-right"></i></a>
                    <a href="?page={{ reviews_objects.paginator.num_pages }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% include '../footer.html' %}

templates/reviews/your_reviews.html
{% include '../head.html' %}
{% include '../navbar.html' %}

{% load filters %}
<section class="mb-3">
    <div class="container-lg">
        <h2 class="my-4">Panel redaktora</h2>
        <div class="row">
            <div class="col-lg-2 border-end">
                <h3 class="my-2 mt-3 fs-4">Akcje</h3>
                <div class="btn-group-vertical">
                    <a href="{% url 'addReviews' %}" class="btn btn-primary btn-block">Dodaj recenzje</a>
                </div>
            </div>
            <div class="col-lg">
                <h3 class="m-2 mb-4 fs-4">Twoje recenzje</h3>
                {% if user_reviews %}
                    {% for review,last in user_reviews %}
                        <div class="card my-2">
                            <div class="card-body">
                                <div class="row">
                                    <h4 class="pb-3 fs-5 border-bottom">{{review.title}}</h4>
                                    <div class="col-md border-end">
                                        <p>{{review.lead|slice:":128"|safe}}{% if review.lead|length > 128 %}...{% endif %}</p>
                                        <span class="text-muted">Ostatnio zmodyfikowane: {{last}}</span>
                                    </div>
                                    <div class="col-md text-center">
                                        <a href="{% url 'editReviews' id=review.id %}" class="btn btn-secondary mx-2 mt-3">Edytuj</a>
                                        <a href="{% url 'deleteReviews' id=review.id %}" class="btn btn-danger mt-3">Usuń</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="card">
                        <div class="card-body">
                            <h4 class="pb-3 fs-5 border-bottom">Brak recenzji</h4>
                            <p class="card-text text-muted">Dodaj recenzje w sekcji Akcje</p>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>


{% include '../footer.html' %}