GameNet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('accounts.urls')),
    path('games/',include('games.urls')),
    path('news/',include('news.urls')),
    path('reviews/',include('reviews.urls')),
    path('moderation/',include('moderation.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.urls import path
from games import views

urlpatterns = [
    path("ranking/", views.ranking, name="ranking"),
    path("list/", views.game_list, name="gameList"),
    path("<id>/", views.game_site, name="game"),
    path("delete/<id>", views.deleteRating, name="deleteRating"),
    path("edit/<id>", views.editRating, name="editRating"),
    path("", views.search, name="search")
]

news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path("your_news/", views.your_news, name="yourNews"),
    path("add/", views.add, name='addNews'),
    path("delete/<id>/", views.delete, name='deleteNews'),
    path("edit/<id>/", views.edit, name='editNews'),
    path("<id>/", views.news_site, name="news"),
    path("",views.news_list, name="newsList")
]

games/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from cloudinary.models import CloudinaryField

# Create your models here.

class Game(models.Model):
    title = models.CharField(max_length=128, help_text="Tytuł gry")
    developer = models.CharField(max_length=128, help_text="Developer")
    description = models.TextField(max_length=1024, help_text="Opis gry")
    release_date = models.DateField(null=True, blank=True, help_text="Data wydania gry")
    image = CloudinaryField("game_image", null=True, blank=True)
    image_link = models.CharField(max_length=512, help_text="Link do zdjęcia", null=True, blank=True)
    trailer = models.CharField(max_length=512, help_text="Link do trailera gry", null=True, blank=True)

    def __str__(self) -> str:
        return self.title + " - " + self.developer

class Rating(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.SET_NULL)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    stars = models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    description = models.TextField(max_length=512, help_text="Twoja opinia", null=True, blank=True)
    accepted = models.BooleanField(null=True, default=None)
    created_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.game.title

games/forms.py
from django.forms import ModelForm
from .models import Rating, Game

class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ["stars","description"]

games/views.py
from email.utils import format_datetime
from platform import release
from django.shortcuts import redirect, render
from django.db.models import Avg, Q, Count
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from babel.dates import format_date, format_datetime

from news.models import News
from .models import Rating,Game
from .yt_id_parser import get_yt_id
from .forms import RatingForm
from reviews.models import Review

from itertools import chain

# Create your views here.

def game_site(request, id):
    game = Game.objects.get(pk=id)
    
    if game.trailer:
        trailer_id = get_yt_id(game.trailer)
    else:
        trailer_id = None
    
    form = RatingForm()

    if request.method == "POST":
        form = RatingForm(request.POST)

        if form.is_valid():
            rating = form.save(commit=False)
            rating.author = request.user
            rating.game = game
            rating.save()
            messages.success(request, "Twoja opinia została przekazana do moderacji. Będziesz mógł ją zobaczyć na stronie gdy zostanie zaakceptowana.")
            form = RatingForm()

    ratings = Rating.objects.filter(game = game).filter(accepted = True)

    if ratings:
        avg = ratings.aggregate(Avg("stars"))
    else:
        avg = None

    last_edit_dates = Rating.objects.filter(game = game).values_list("edit_date",flat=True)
    last_edit_formated = []

    for last in last_edit_dates:
        last_edit_formated.append(format_datetime(last, locale="pl_PL"))
    
    reviews_avg = Review.objects.filter(game = game).aggregate(Avg("points"))['points__avg']

    context = {
        'game': game, 
        'ratings': zip(ratings,last_edit_formated) if ratings else None, 
        'ratings_count': ratings.count() if ratings else None,
        'avg': avg, 
        'release_date': format_date(game.release_date, locale="pl_PL"), 
        'trailer_id': trailer_id,
        'form': form,
        'reviews_avg': reviews_avg,
    }
    return render(request, "games/game_template.html", context)


def ranking(request):
    games = Game.objects.filter(rating__isnull=False, rating__accepted=True).annotate(avg_rating=Avg("rating__stars")).annotate(rating_count=Count("rating")).order_by("-avg_rating")[:20]
    context = {'games': games}
    return render(request, "games/ranking.html", context)


@login_required
def deleteRating(request, id):
    rating = Rating.objects.get(pk=id)
    rating.delete()
    return redirect('profile')

@login_required
def editRating(request, id):
    rating = Rating.objects.get(pk=id)

    if request.method == 'POST':
        form = RatingForm(request.POST, instance=rating)
        if form.is_valid():
            form.save()
            return redirect('profile')

    form = RatingForm(instance=rating)

    context = {'form': form, 'game_title': rating.game.title}
    return render(request, "games/edit_rating.html", context)

@csrf_exempt
def search(request):
    page = request.GET.get('page', 1)

    if request.GET.get('search'):
        searched_games = Game.objects.filter(Q(title__icontains = request.GET.get('search')) | Q(description__icontains = request.GET.get('search')))
        searched_reviews = Review.objects.filter(Q(title__icontains = request.GET.get('search')) | Q(lead__icontains = request.GET.get('search')) | Q(content__icontains = request.GET.get('search')) | Q(summary__icontains = request.GET.get('search')))
        searched_news = News.objects.filter(Q(title__icontains = request.GET.get('search')) | Q(lead__icontains = request.GET.get('search')) | Q(content__icontains = request.GET.get('search')))
    else:
        searched_games = Game.objects.all()
        searched_reviews = Review.objects.all()
        searched_news = News.objects.all()
    
    searched_items = list(chain(searched_games, searched_news, searched_reviews))

    paginator = Paginator(searched_items, 10)

    try:
        searched_items = paginator.get_page(page)
    except PageNotAnInteger:
        searched_items = paginator.get_page(1)
    except EmptyPage:
        searched_items = paginator.page(paginator.num_pages)

    context = {'searched_items': searched_items}
    return render(request, "games/search.html",context)

def game_list(request):
    page = request.GET.get('page', 1)

    if request.GET.get('search'):
        searched_games = Game.objects.filter(Q(title__icontains = request.GET.get('search')) | Q(description__icontains = request.GET.get('search')))
    else:
        searched_games = Game.objects.all()
    
    paginator = Paginator(searched_games, 10)

    try:
        searched_games = paginator.get_page(page)
    except PageNotAnInteger:
        searched_games = paginator.get_page(1)
    except EmptyPage:
        searched_games = paginator.page(paginator.num_pages)

    context = {'searched_games': searched_games}
    return render(request, "games/game_list.html",context)

templates/games/edit_rating.html
{% include '../head.html' %}
{% include '../navbar.html' %}

{% load crispy_forms_tags %}

<section>
    <div class="container-lg mt-4">
        <h2>Edytuj opinię o grze {{game_title}}</h2>
        <div class="my-3 mb-4 px-3">
            <form action="" method="post">
                {% csrf_token %}

                <div class="row px-3">
                    <div class="col-md-10">
                        <label for="id_description">Opis</label>
                        {{form.description|as_crispy_field}}
                    </div>
                
                    <div class="col-md-2 float-left">
                        <label for="id_stars">Ocena (0-5)</label>
                        {{form.stars|as_crispy_field}}
                        <button class="btn btn-primary my-3" type="submit">Zapisz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>


{% include '../footer.html' %}

templates/games/game_list.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section>
    <div class="container-lg">
        <h2 class="my-4">Lista gier</h2>

        {% if searched_games %}
        {% for game in searched_games %}
        <a href="{% url 'game' id=game.pk %}" class="text-reset text-decoration-none">
        <div class="card my-3">
            <div class="row">
                <div class="col-3">
                    {% if game.image %}
                    <img src="{{ game.image.url }}" alt="Game image" class="img-fluid rounded-start"/>
                    {% elif game.image_link %}
                    <img src="{{ game.image_link }}" alt="Game image" class="img-fluid rounded-start"/>
                    {% else %}
                    <img src="https://res.cloudinary.com/dzxo9mpqc/image/upload/v1656005252/no-photo-available_gyrfyl.png" alt="game image" class="img-fluid rounded-start">
                    {% endif %}
                </div>
                <div class="col">
                    <div class="card-body">
                        <h5 class="card-title">{{game.title}}</h5>
                        <p class="card-text">{{game.description|slice:":256"}}{% if game.description|length > 256 %}...{% endif %}</p>
                    </div>
                </div>
            </div>
        </div>
        </a>
        
        {% endfor %}
        {% else %}

        <div class="card my-3">
            <div class="card-body">
                <h3 class="fs-4">Brak wyszukiwań</h3>
                <span class="text-muted">Nie znaleziono gier na podstawie twojego wyszukiwania</span>
            </div>
        </div>
        
        {% endif %}

    </div>
</section>

<section>
    <div class="container my-4">
        <div class="btn-toolbar d-flex justify-content-center">
            <div class="btn-group mx-3">
                {% if searched_games.has_previous %}
                    <a href="?page=1" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-left"></i></a>
                    <a href="?page={{ searched_games.previous_page_number }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-left"></i></a>
                {% endif %}
            </div>
                <span class="border rounded border-secondary text-muted p-2">{{searched_games.number}}</span>
            <div class="btn-group mx-3">
                {% if searched_games.has_next %}
                    <a href="?page={{ searched_games.next_page_number }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-right"></i></a>
                    <a href="?page={{ searched_games.paginator.num_pages }}" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% include '../footer.html' %}

templates/games/game_template.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section class="bg-light">
    <div class="container-lg border rounded my-3">
        <div class="row m-4 text-center">
            <h1> {{game.title}} </h1>
        </div>
        <div class="row my-3 d-flex justify-content-center">
            <div class="col-xl mx-4 game-img">
                <img src="{% if game.image %} {{ game.image.url }} {% elif game.image_link %} {{game.image_link}} {% else %} https://res.cloudinary.com/dzxo9mpqc/image/upload/v1656005252/no-photo-available_gyrfyl.png {% endif %}" alt="Game image" class="img-fluid rounded">
            </div>
            <div class="col-xl my-4 my-xl-1 text-end">
                <p>
                    {{game.description}}
                </p>
                <p>
                    <b>Developer: </b> {{game.developer}}
                </p>
                <p>
                    <b>Data wydania: </b> {% if release_date %} {{release_date}} {% else %} - {% endif %}
                </p>
            </div>
            <div class="col-xl">
                <div class="card mx-2">
                    <div class="card-body">
                        <h5 class="card-title">Średnia ocen graczy</h5>
                        <a href="#ratings" class="text-reset text-decoration-none">
                        <div style="width: 60px; height: 50px;" class="col-2 fs-2 mt-3 bg-{% if avg.stars__avg <= 2.5 %}danger{% elif avg.stars__avg < 4.0 %}warning{% else %}success{% endif %} rounded text-light d-flex justify-content-center">
                            <div class="mx-2">{% if avg %}{{avg.stars__avg}}{% else %}-{% endif %}</div>
                        </div>
                        <p class="card-text m-1">{% if ratings_count %}z {{ratings_count}} opinii użytkowników{% else %}brak opinii na temat gry{% endif %}</p>
                        </a>
                        
                        <h5 class="card-title mt-4">Średnia ocen recenzentów</h5>
                        <div style="width: 70px; height: 70px; display: flex; justify-content: center; align-items: center;" class="fs-2 mt-3 bg-{% if reviews_avg <= 3.3 %}danger{% elif reviews_avg < 6.6 %}warning{% else %}success{% endif %} rounded-circle text-light d-flex justify-content-center">
                            <div class="mx-2">{% if reviews_avg %}{{reviews_avg}}{% else %}-{% endif %}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% if trailer_id %}

<div class="container-lg">
    <h2 class="my-2">Trailer</h2>
    <div class="d-flex justify-content-center border rounded p-0 my-1">
        <div class="p-5 my-3 w-50 border ratio ratio-16x9">
            <iframe
            src="https://www.youtube.com/embed/{{trailer_id}}">
            </iframe> 
        </div>
    </div>
</div>


{% endif %}

{% load crispy_forms_tags %}

<section id="ratings" class="bg-light">
    <div class="container-lg">
        <h2 class="my-2" >Oceny i opinie</h2>
        {% for message in messages %}
                <p class="alert alert-success d-flex align-items-center mt-5 px-3" role="alert">
                    <span class="mx-auto fs-5">{{message}}</span>
                </p>
        {% endfor %}
        <div class="my-3 mb-4 px-3">
            {% if request.user.is_authenticated %}
                <h3 class="fs-5">Dodaj opinię</h3>
                <form action="" method="post">
                    {% csrf_token %}

                    <div class="row px-3">
                        <div class="col-md-10">
                            <label for="id_description">Opis</label>
                            {{form.description|as_crispy_field}}
                        </div>
                    
                        <div class="col-md-2 float-left">
                            <label for="id_stars">Ocena (0-5)</label>
                            {{form.stars|as_crispy_field}}
                            <button class="btn btn-primary my-3" type="submit">Dodaj</button>
                        </div>
                    </div>
                </form>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-primary mx-3">Zaloguj się</a> aby dodawać opinie.
            {% endif %}
        </div>
        
        {% if ratings %}
            {% for rating,last in ratings %}
            <div class="card my-3">
                <div class="card-header">Autor: {% if rating.author %}{{rating.author.username}}{% else %}<span class="text-muted">[Konto usunięto]</span>{% endif %}</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            {% if rating.description %}
                                {{rating.description}}
                            {% else %}
                                <span class="text-muted">Brak opisu</span>
                            {% endif %}
                        </div>
                        <div class="col d-flex justify-content-center border-start" style="max-height: 25px;">
                            Ocena: 
                            <div class="mx-2 bg-{% if rating.stars <= 2.5 %}danger{% elif rating.stars < 4.0 %}warning{% else %}success{% endif %} rounded text-light">
                                <div class="mx-2">{{rating.stars}}</div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <span class="text-muted">Ostatnio zmodyfikowane: {{last}}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="card my-3">
                <div class="card-body text-muted">
                    Brak opinii na temat tej gry
                </div>
            </div>
        {% endif %}
    </div>
</section>


{% include '../footer.html' %}

templates/games/ranking.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section>
    <div class="container-lg">
        <h2 class="my-4">Top 20 gier według graczy</h2>

        {% if games %}
        {% for game in games %}
        <a href="{% url 'game' id=game.pk %}" class="text-reset text-decoration-none">
        <div class="card my-4">
            <div class="row">
                <div class="col-md-1 text-center my-auto">
                    <span class="fs-3">#{{forloop.counter}}</span>
                </div>
                <div class="col-md-3">
                    {% if game.image %}
                    <img src="{{ game.image.url }}" alt="Game image" class="img-fluid rounded-start"/>
                    {% elif game.image_link %}
                    <img src="{{ game.image_link }}" alt="Game image" class="img-fluid rounded-start"/>
                    {% else %}
                    ----
                    {% endif %}
                </div>
                <div class="col-md">
                    <div class="card-body">
                        <h5 class="card-title">{{game.title}}</h5>
                        <p class="card-text">{{game.description|slice:":256"}}{% if game.description|length > 256 %}...{% endif %}</p>
                    </div>
                </div>
                <div class="col-md-2 me-3">
                    <h5 class="mt-4">Średnia ocen graczy</h5>
                    <div style="width: 60px; height: 50px;" class="col-2 fs-2 mt-3 bg-{% if game.avg_rating <= 2.5 %}danger{% elif game.avg_rating < 4.0 %}warning{% else %}success{% endif %} rounded text-light d-flex justify-content-center">
                        <div class="mx-2">{{game.avg_rating}}</div>
                    </div>
                    <p class="m-1">z {{game.rating_count}} opinii użytkowników</p>
                </div>
            </div>
        </div>
        </a>
        
        {% endfor %}
        {% else %}

        <div class="card my-3">
            <div class="card-body">
                <h3 class="fs-4">Brak rankingu</h3>
                <span class="text-muted">Ranking pojawi się gdy pojawią się pierwsze opinie gier</span>
            </div>
        </div>
        
        {% endif %}

    </div>
</section>

{% include '../footer.html' %}

templates/games/search.html
{% include '../head.html' %}
{% include '../navbar.html' %}

<section>
    <div class="container-lg">
        <h2 class="my-4">Wyniki wyszukiwania</h2>

        {% if searched_items %}
        {% for item in searched_items %}
        <a href="{% if item.description %}{% url 'game' id=item.pk %}{% elif item.summary %}{% url 'review' id=item.pk %}{% else %}{% url 'news' id=item.pk %}{% endif %}" class="text-reset text-decoration-none">
        <div class="card my-3">
            <div class="row">
                <div class="col-md-3">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" alt="item image" class="img-fluid rounded-start"/>
                    {% elif item.image_link %}
                    <img src="{{ item.image_link }}" alt="item image" class="img-fluid rounded-start"/>
                    {% else %}
                    <img src="https://res.cloudinary.com/dzxo9mpqc/image/upload/v1656005252/no-photo-available_gyrfyl.png" alt="item image" class="img-fluid rounded-start">
                    {% endif %}
                </div>
                <div class="col-md">
                    <div class="card-body">
                        <h5 class="card-title">{{item.title}}</h5>
                        <p class="card-text">{% if item.description %}{{item.description|slice:":256"}}{% if item.description|length > 256 %}...{% endif %}{% elif item.lead %}{{item.lead|slice:":256"}}{% if item.lead|length > 256 %}...{% endif %}{% endif %}</p>
                    </div>
                </div>
            </div>
        </div>
        </a>
        
        {% endfor %}
        {% else %}

        <div class="card my-3">
            <div class="card-body">
                <h3 class="fs-4">Brak wyszukiwań</h3>
                <span class="text-muted">Nie znaleziono gier na podstawie twojego wyszukiwania</span>
            </div>
        </div>
        
        {% endif %}

    </div>
</section>

<section>
    <div class="container my-4">
        <div class="btn-toolbar d-flex justify-content-center">
            <div class="btn-group mx-3">
                {% if searched_items.has_previous %}
                    <a href="?page=1&search={{request.GET.search}}" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-left"></i></a>
                    <a href="?page={{ searched_items.previous_page_number }}&search={{request.GET.search}}" class="btn btn-outline-secondary"><i class="bi bi-chevron-left"></i></a>
                {% endif %}
            </div>
                <span class="border rounded border-secondary text-muted p-2">{{searched_items.number}}</span>
            <div class="btn-group mx-3">
                {% if searched_items.has_next %}
                    <a href="?page={{ searched_items.next_page_number }}&search={{request.GET.search}}" class="btn btn-outline-secondary"><i class="bi bi-chevron-right"></i></a>
                    <a href="?page={{ searched_items.paginator.num_pages }}&search={{request.GET.search}}" class="btn btn-outline-secondary"><i class="bi bi-chevron-double-right"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% include '../footer.html' %}